### ISSUE TITLE
Fix NullPointer on `invalidateScrollingChild`

### ISSUE THREAD

**Issue by renezuidhof** [xcc3641/ExViewPagerBottomSheet#2]
It looks like the fix from this PR is not available in the latest tag. Is that correct?

https://github.com/xcc3641/ExViewPagerBottomSheet/pull/1

**Comment by renezuidhof** [comment]
Can you have a look at this? The fix that was merged is not available in the latest release (1.2).

**Comment by xcc3641** [comment]
1.3

**Comment by renezuidhof** [comment]
Thanks! It seems the 1.3 package is not available though. I'm getting this message:
`Failed to resolve: com.github.xcc3641:ExViewPagerBottomSheet:1.3`

Any idea why?
